---
apiVersion: v1
kind: Deployment
metadata:
  name: my_app
  labels:
    app: my_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my_app
  containers:
    - name: my_app
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
      volumeMounts:
        - name: data
          mountPath: /data
        - name: config 
          mountPath: /config
  volumes:
    - name: my_persistentvolume
      persistentVolumeClaim:
        claimName: my_efs-claim