---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my_persistentvolume
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my_efs-sc
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /tmp
    server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my_efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my_efs-sc
  resources:
    requests:
      storage: 2Gi
